"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$python\
$lua\
$status\
\n$character\
"""

palette = 'catppuccin_macchiato'

[directory]
style = "fg:blue"
format = "[$path ]($style)"
truncation_length = 5
truncate_to_repo=false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Projects" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:yellow"
format = '[[$symbol $branch ](fg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:yellow)]($style)'

[nodejs]
symbol = ""
format = '[[$symbol( $version) ](fg:mauve)]($style)'

[c]
symbol = ""
format = '[[$symbol( $version(-$name)) ](fg:mauve)]($style)'

[rust]
symbol = ""
format = '[[$symbol( $version) ](fg:mauve)]($style)'

[golang]
symbol = ""
format = '[[$symbol( $version) ](fg:mauve)]($style)'

[php]
symbol = ""
format = '[[$symbol( $version) ](fg:mauve)]($style)'

[java]
symbol = " "
format = '[[$symbol( $version) ](fg:mauve)]($style)'

[python]
symbol = ""
format = '[[$symbol( $version)(\(#$virtualenv\)) ](fg:mauve)]($style)'

[lua]
symbol = ""
format = '[[$symbol( $version) ](fg:mauve)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[character]
disabled = false
format = '$symbol '
success_symbol = '[ \$](bold fg:green)'
error_symbol = '[ \$](bold fg:red)'

[status]
disabled = false

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
